name: Daily Udemy Link Extractor

on:
  schedule:
    - cron: '0 3 * * *'  # runs at 03:00 UTC (~8:30 AM IST)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright telethon requests
          playwright install chromium

      - name: Run Telegram Extractor
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELETHON_STRING_SESSION: ${{ secrets.TELETHON_STRING_SESSION }}
        run: python main.py